Update svd_schema.txt
Open-CMSIS-Pack/svd-spec pull request #4
Opened 2023-09-27 14:45 UTC by jkrech

Fixed description for choices of bit-field specifications, where child elements did not match parent.

2023-09-27 15:23 UTC, JonatanAntoni requested changes
I think we should keep the order (1, 2, 3) in the table. Having (2, 1, 3) looks a bit funny.

2023-09-27 15:23 UTC, JonatanAntoni commented on doxygen/src/svd_schema.txt
> +        <td colspan="4"><em>2. bitRangeOffsetWidthStyle</em></td>
This leads to missordering in the generated docs:

```suggestion
        <td colspan="4"><em>1. bitRangeOffsetWidthStyle</em></td>
```

2023-09-27 15:30 UTC, jkrech commented
Well spotted. Thanks.

2023-09-27 15:37 UTC, AndreySmirnov81 commented
Maybe it's better to keep the same order as in SVD Schema?

https://github.com/Open-CMSIS-Pack/svd-spec/blob/2567db1a77f12f30776ca986cda8448897a78242/schema/CMSIS-SVD.xsd#L452-L459

2024-02-21 09:31 UTC, JonatanAntoni commented
@jkrech, is this still relevant? Shall we update the PR and get it merged?

2024-02-21 09:56 UTC, JonatanAntoni approved these changes

2024-02-21 10:29 UTC, merged